<?xml version ="1.0"?>
<!-- The Document Type Definition (DTD) for the file -->
<!DOCTYPE CONFIGURATION [
<!ELEMENT CONFIGURATION (SERVER, MODULE*)>
<!ELEMENT SERVER (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ELEMENT MODULE (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ATTLIST MODULE
	NAME CDATA #REQUIRED>
<!ELEMENT PREF (#PCDATA)>
<!ATTLIST PREF
	NAME CDATA #REQUIRED
	TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Float32|Float64|Bool16|Bool8|char) "char">
<!ELEMENT LIST-PREF (VALUE*)>
<!ELEMENT VALUE (#PCDATA)>
<!ATTLIST LIST-PREF
	NAME CDATA #REQUIRED
	TYPE  (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Float32|Float64|Bool16|Bool8|char) "char">
<!ELEMENT OBJECT (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ATTLIST OBJECT
	NAME CDATA #REQUIRED>
<!ELEMENT LIST-OBJECT (OBJECT-VALUE*)>
<!ELEMENT OBJECT-VALUE (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ATTLIST LIST-OBJECT
	NAME CDATA #REQUIRED>
]>
<CONFIGURATION>
	<SERVER>
		<LIST-PREF NAME="rtsp_port" TYPE="UInt16" >
			<VALUE>554</VALUE>
		</LIST-PREF>
		<PREF NAME="default_authorization_realm" >EasyDarwin</PREF>
		<PREF NAME="do_report_http_connection_ip_address" TYPE="Bool16" >disabled</PREF>
		<PREF NAME="tcp_seconds_to_buffer" TYPE="Float32" >.5</PREF>
		<PREF NAME="max_tcp_buffer_size" TYPE="UInt32" >200000</PREF>
		<PREF NAME="min_tcp_buffer_size" TYPE="UInt32" >8192</PREF>
		<PREF NAME="error_logging" TYPE="Bool16" >true</PREF>
		<PREF NAME="screen_logging" TYPE="Bool16" >true</PREF>
		<PREF NAME="error_logfile_verbosity" TYPE="UInt32" >3</PREF>
		<PREF NAME="error_logfile_size" TYPE="UInt32" >512000</PREF>
		<PREF NAME="error_logfile_interval" TYPE="UInt32" >7</PREF>
		<PREF NAME="error_logfile_dir" >./Logs/</PREF>
		<PREF NAME="error_logfile_name" >EasyDarwin</PREF>
		<PREF NAME="module_folder" >./QTSSModules</PREF>
		<PREF NAME="safe_play_duration" TYPE="UInt32" >600</PREF>
		<PREF NAME="average_bandwidth_update" TYPE="UInt32" >60</PREF>
		<PREF NAME="total_bytes_update" TYPE="UInt32" >1</PREF>
		<PREF NAME="auto_restart" TYPE="Bool16" >true</PREF>
		<PREF NAME="break_on_assert" TYPE="Bool16" >false</PREF>
		<PREF NAME="bind_ip_addr" >0</PREF>
		<PREF NAME="movie_folder" >./Movies/</PREF>
		<PREF NAME="maximum_bandwidth" TYPE="SInt32" >1024000</PREF>
		<PREF NAME="maximum_connections" TYPE="SInt32" >10000</PREF>
		<PREF NAME="rtp_timeout" TYPE="UInt32" >120</PREF>
		<PREF NAME="real_rtsp_timeout" TYPE="UInt32" >30</PREF>
		<PREF NAME="rtsp_timeout" TYPE="UInt32" >0</PREF>
		<PREF NAME="run_user_name" ></PREF>
		<PREF NAME="run_group_name" ></PREF>
		<PREF NAME="drop_all_packets_delay" TYPE="SInt32" >2500</PREF>
		<PREF NAME="drop_all_video_delay" TYPE="SInt32" >1750</PREF>
		<PREF NAME="thin_all_the_way_delay" TYPE="SInt32" >1500</PREF>
		<PREF NAME="always_thin_delay" TYPE="SInt32" >750</PREF>
		<PREF NAME="start_thinning_delay" TYPE="SInt32" >0</PREF>
		<PREF NAME="start_thicking_delay" TYPE="SInt32" >250</PREF>
		<PREF NAME="thick_all_the_way_delay" TYPE="SInt32" >-2000</PREF>
		<PREF NAME="quality_check_interval" TYPE="UInt32" >1000</PREF>
		<PREF NAME="append_source_addr_in_transport" TYPE="Bool16" >false</PREF>
		<PREF NAME="max_retransmit_delay" TYPE="UInt32" >500</PREF>
		<PREF NAME="small_window_size" TYPE="UInt32" >24</PREF>
		<PREF NAME="medium_window_size" TYPE="UInt32" >48</PREF>
		<PREF NAME="large_window_size" TYPE="UInt32" >64</PREF>
		<PREF NAME="window_size_threshold" TYPE="UInt32" >200</PREF>
		<PREF NAME="window_size_max_threshold" TYPE="UInt32" >1000</PREF>
		<PREF NAME="ack_logging_enabled" TYPE="Bool16" >false</PREF>
		<PREF NAME="rtcp_poll_interval" TYPE="UInt32" >100</PREF>
		<PREF NAME="rtcp_rcv_buf_size" TYPE="UInt32" >768</PREF>
		<PREF NAME="send_interval" TYPE="UInt32" >50</PREF>
		<PREF NAME="max_send_ahead_time" TYPE="UInt32" >25</PREF>
		<PREF NAME="reliable_udp_slow_start" TYPE="Bool16" >true</PREF>
		<PREF NAME="auto_delete_sdp_files" TYPE="Bool16" >false</PREF>
		<PREF NAME="authentication_scheme" >digest</PREF>
		<PREF NAME="sdp_file_delete_interval_seconds" TYPE="UInt32" >10</PREF>
		<PREF NAME="reliable_udp" TYPE="Bool16" >true</PREF>
		<PREF NAME="reliable_udp_dirs" >\</PREF>
		<PREF NAME="reliable_udp_printfs" TYPE="Bool16" >false</PREF>
		<PREF NAME="RTSP_error_message" TYPE="Bool16" >false</PREF>
		<PREF NAME="run_num_threads" TYPE="UInt32" >10</PREF>
		<PREF NAME="overbuffer_rate" TYPE="Float32" >2.0</PREF>
		<PREF NAME="RTSP_debug_printfs" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_monitor_stats_file" TYPE="Bool16" >true</PREF>
		<PREF NAME="monitor_stats_file_interval_seconds" TYPE="UInt32" >10</PREF>
		<PREF NAME="monitor_stats_file_name" >server_status</PREF>
		<PREF NAME="enable_packet_header_printfs" TYPE="Bool16" >false</PREF>
		<PREF NAME="packet_header_printf_options" >rtp;rr;sr;app;ack;</PREF>
		<PREF NAME="alt_transport_src_ipaddr" ></PREF>
		<PREF NAME="auto_start" TYPE="Bool16" >false</PREF>
		<PREF NAME="RTSP_server_info" TYPE="Bool16" >true</PREF>
		<PREF NAME="pid_file" >EasyDarwin.pid</PREF>
		<PREF NAME="force_logs_close_on_write" TYPE="Bool16" >false</PREF>
		<PREF NAME="disable_thinning" TYPE="Bool16" >false</PREF>
		<LIST-PREF NAME="player_requires_rtp_header_info" >
			<VALUE>Android</VALUE>
			<VALUE>IOS</VALUE>
		</LIST-PREF>
		<LIST-PREF NAME="player_requires_bandwidth_adjustment" >
			<VALUE>Android</VALUE>
			<VALUE>IOS</VALUE>
		</LIST-PREF>
		<LIST-PREF NAME="player_requires_no_pause_time_adjustment" >
			<VALUE>Android</VALUE>
			<VALUE>IOS</VALUE>
		</LIST-PREF>
		<PREF NAME="enable_3gpp_protocol" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_3gpp_protocol_rate_adaptation" TYPE="Bool16" >true</PREF>
		<PREF NAME="3gpp_protocol_rate_adaptation_report_frequency" TYPE="UInt16" >1</PREF>
		<PREF NAME="default_stream_quality" TYPE="UInt16" >0</PREF>
		<PREF NAME="player_requires_rtp_start_time_adjust" >Real</PREF>
		<PREF NAME="enable_3gpp_debug_printfs" TYPE="Bool16" >false</PREF>
		<PREF NAME="enable_udp_monitor_stream" TYPE="Bool16" >false</PREF>
		<PREF NAME="udp_monitor_video_port" TYPE="UInt16" >5002</PREF>
		<PREF NAME="udp_monitor_audio_port" TYPE="UInt16" >5004</PREF>
		<PREF NAME="udp_monitor_dest_ip" >127.0.0.1</PREF>
		<PREF NAME="udp_monitor_src_ip" >0.0.0.0</PREF>
		<PREF NAME="enable_allow_guest_default" TYPE="Bool16" >true</PREF>
		<PREF NAME="run_num_rtsp_threads" TYPE="UInt32" >3</PREF>
		<PREF NAME="player_requires_disable_3gpp_rate_adapt" ></PREF>
		<PREF NAME="player_requires_3gpp_target_time" ></PREF>
		<PREF NAME="3gpp_target_time_milliseconds" TYPE="UInt32" >3000</PREF>
		<PREF NAME="player_requires_disable_thinning" ></PREF>
		<PREF NAME="http_service_port" TYPE="UInt16" >8080</PREF>
	</SERVER>
	<MODULE NAME="QTSSAccessLogModule" >
		<PREF NAME="request_logfile_interval" TYPE="UInt32" >7</PREF>
		<PREF NAME="request_logfile_size" TYPE="UInt32" >10240000</PREF>
		<PREF NAME="request_logfile_dir" >./Logs</PREF>
		<PREF NAME="request_logfile_name" >EasyDarwin_access</PREF>
		<PREF NAME="request_logtime_in_gmt" TYPE="Bool16" >true</PREF>
		<PREF NAME="request_logging" TYPE="Bool16" >true</PREF>
	</MODULE>
	<MODULE NAME="QTSSFileModule" >
		<PREF NAME="sdp_url" ></PREF>
		<PREF NAME="admin_email" ></PREF>
		<PREF NAME="max_allowed_speed" TYPE="Float32" >4.000000</PREF>
		<PREF NAME="flow_control_probe_interval" TYPE="UInt32" >10</PREF>
		<PREF NAME="enable_shared_file_buffers" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_private_file_buffers" TYPE="Bool16" >true</PREF>
		<PREF NAME="num_shared_buffer_increase_per_session" TYPE="UInt32" >2</PREF>
		<PREF NAME="shared_buffer_unit_k_size" TYPE="UInt32" >32</PREF>
		<PREF NAME="private_buffer_unit_k_size" TYPE="UInt32" >32</PREF>
		<PREF NAME="num_shared_buffer_units_per_buffer" TYPE="UInt32" >0</PREF>
		<PREF NAME="num_private_buffer_units_per_buffer" TYPE="UInt32" >1</PREF>
		<PREF NAME="max_shared_buffer_units_per_buffer" TYPE="UInt32" >8</PREF>
		<PREF NAME="max_private_buffer_units_per_buffer" TYPE="UInt32" >8</PREF>
		<PREF NAME="add_seconds_to_client_buffer_delay" TYPE="Float32" >0.000000</PREF>
		<PREF NAME="record_movie_file_sdp" TYPE="Bool16" >false</PREF>
		<PREF NAME="enable_movie_file_sdp" TYPE="Bool16" >false</PREF>
		<PREF NAME="enable_player_compatibility" TYPE="Bool16" >true</PREF>
		<PREF NAME="compatibility_adjust_sdp_media_bandwidth_percent" TYPE="UInt32" >50</PREF>
		<PREF NAME="compatibility_adjust_rtp_start_time_milli" TYPE="SInt64" >500</PREF>
		<PREF NAME="allow_invalid_hint_track_refs" TYPE="Bool16" >false</PREF>
	</MODULE>
	<MODULE NAME="QTSSMP3StreamingModule" >
		<PREF NAME="mp3_streaming_enabled" TYPE="Bool16" >true</PREF>
		<PREF NAME="mp3_broadcast_password" > </PREF>
		<PREF NAME="mp3_broadcast_buffer_size" TYPE="UInt32" >8192</PREF>
		<PREF NAME="mp3_max_flow_control_time" TYPE="SInt32" >10000</PREF>
		<PREF NAME="mp3_request_logfile_name" >mp3_access</PREF>
		<PREF NAME="mp3_request_logfile_dir" >./Logs</PREF>
		<PREF NAME="mp3_request_logging" TYPE="Bool16" >true</PREF>
		<PREF NAME="mp3_request_logfile_size" TYPE="UInt32" >10240000</PREF>
		<PREF NAME="mp3_request_logfile_interval" TYPE="UInt32" >7</PREF>
		<PREF NAME="mp3_request_logtime_in_gmt" TYPE="Bool16" >true</PREF>
	</MODULE>
	<MODULE NAME="QTSSWebStatsModule" >
		<PREF NAME="web_stats_url" ></PREF>
	</MODULE>
	<MODULE NAME="QTSSHttpFileModule" >
		<PREF NAME="http_xfer_enabled" TYPE="Bool16" >false</PREF>
		<PREF NAME="http_folder" >./http</PREF>
		<PREF NAME="http_logging" TYPE="Bool16" >true</PREF>
		<PREF NAME="http_logfile_name" >Http</PREF>
		<PREF NAME="http_logfile_dir" >./httpLogs</PREF>
		<PREF NAME="http_logfile_size" TYPE="UInt32" >256000</PREF>
		<PREF NAME="http_logfile_interval" TYPE="UInt32" >7</PREF>
	</MODULE>
	<MODULE NAME="QTSSReflectorModule" >
		<PREF NAME="reflector_bucket_size" TYPE="UInt32" >16</PREF>
		<PREF NAME="reflector_delay" TYPE="UInt32" >100</PREF>
		<PREF NAME="allow_non_sdp_urls" TYPE="Bool16" >false</PREF>
		<PREF NAME="enable_broadcast_push" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_broadcast_announce" TYPE="Bool16" >true</PREF>
		<PREF NAME="max_broadcast_announce_duration_secs" TYPE="UInt32" >0</PREF>
		<PREF NAME="allow_duplicate_broadcasts" TYPE="Bool16" >true</PREF>
		<PREF NAME="enforce_static_sdp_port_range" TYPE="Bool16" >false</PREF>
		<PREF NAME="maximum_static_sdp_port" TYPE="UInt16" >65535</PREF>
		<PREF NAME="minimum_static_sdp_port" TYPE="UInt16" >20000</PREF>
		<PREF NAME="timeout_stream_SSRC_secs" TYPE="UInt32" >30</PREF>
		<PREF NAME="use_one_SSRC_per_stream" TYPE="Bool16" >true</PREF>
		<PREF NAME="kill_clients_when_broadcast_stops" TYPE="Bool16" >false</PREF>
		<PREF NAME="reflector_bucket_offset_delay_msec" TYPE="UInt32" >73</PREF>
		<PREF NAME="reflector_buffer_size_sec" TYPE="UInt32" >1</PREF>
		<PREF NAME="reflector_use_in_packet_receive_time" TYPE="Bool16" >false</PREF>
		<PREF NAME="reflector_in_packet_max_receive_sec" TYPE="UInt32" >60</PREF>
		<PREF NAME="enable_rtp_play_info" TYPE="Bool16" >false</PREF>
		<PREF NAME="timeout_broadcaster_session_secs" TYPE="UInt32" >20</PREF>
		<PREF NAME="authenticate_local_broadcast" TYPE="Bool16" >false</PREF>
		<PREF NAME="disable_overbuffering" TYPE="Bool16" >false</PREF>
		<PREF NAME="max_announced_sdp_length_kbytes" TYPE="UInt32" >0</PREF>
		<PREF NAME="allow_broadcasts" TYPE="Bool16" >true</PREF>
		<PREF NAME="redirect_broadcast_keyword" ></PREF>
		<PREF NAME="redirect_broadcasts_dir" ></PREF>
		<PREF NAME="broadcast_dir_list" ></PREF>
		<PREF NAME="reflector_rtp_info_offset_msec" TYPE="UInt32" >500</PREF>
		<PREF NAME="disable_rtp_play_info" TYPE="Bool16" >false</PREF>
		<PREF NAME="allow_announced_kill" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_play_response_range_header" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_player_compatibility" TYPE="Bool16" >true</PREF>
		<PREF NAME="compatibility_adjust_sdp_media_bandwidth_percent" TYPE="UInt32" >100</PREF>
		<PREF NAME="force_rtp_info_sequence_and_time" TYPE="Bool16" >false</PREF>
		<PREF NAME="BroadcasterGroup" >broadcaster</PREF>
		<PREF NAME="ip_allow_list" >127.0.0.*</PREF>
		<PREF NAME="hls_output_enabled" TYPE="Bool16" >true</PREF>
	</MODULE>
	<MODULE NAME="QTSSFlowControlModule" >
		<PREF NAME="loss_thin_tolerance" TYPE="UInt32" >30</PREF>
		<PREF NAME="num_losses_to_thin" TYPE="UInt32" >3</PREF>
		<PREF NAME="loss_thick_tolerance" TYPE="UInt32" >5</PREF>
		<PREF NAME="num_losses_to_thick" TYPE="UInt32" >6</PREF>
		<PREF NAME="num_worses_to_thin" TYPE="UInt32" >2</PREF>
		<PREF NAME="flow_control_udp_thinning_module_enabled" TYPE="Bool16" >true</PREF>
	</MODULE>
	<MODULE NAME="QTSSRelayModule" >
		<PREF NAME="relay_prefs_file" >./relayconfig.xml</PREF>
		<PREF NAME="relay_stats_url" ></PREF>
	</MODULE>
	<MODULE NAME="QTSSAccessModule" >
		<PREF NAME="modAccess_qtaccessfilename" >qtaccess</PREF>
		<PREF NAME="modAccess_groupsfilepath" >./qtgroups</PREF>
		<PREF NAME="modAccess_usersfilepath" >./qtusers</PREF>
		<PREF NAME="modAccess_enabled" TYPE="Bool16" >true</PREF>
	</MODULE>
	<MODULE NAME="QTSSAdminModule" >
		<PREF NAME="RequestTimeIntervalMilli" TYPE="UInt32" >50</PREF>
		<PREF NAME="LocalAccessOnly" TYPE="Bool16" >true</PREF>
		<PREF NAME="Authenticate" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_remote_admin" TYPE="Bool16" >true</PREF>
		<PREF NAME="IPAccessList" >127.0.0.*</PREF>
		<PREF NAME="AdministratorGroup" >admin</PREF>
		<PREF NAME="http_port" TYPE="UInt16" >8088</PREF>
		<PREF NAME="document_root" >./html/</PREF>
	</MODULE>
	<MODULE NAME="QTSSErrorLogModule" ></MODULE>
	<MODULE NAME="QTSSPosixFileSysModule" ></MODULE>
	<MODULE NAME="EasyHLSModule" >
		<PREF NAME="HTTP_ROOT_DIR" >http://127.0.0.1/</PREF>
		<PREF NAME="M3U8_VERSION" TYPE="UInt32" >3</PREF>
		<PREF NAME="ALLOW_CACHE" TYPE="Bool16" >false</PREF>
		<PREF NAME="TARGET_DURATION" TYPE="UInt32" >4</PREF>
		<PREF NAME="PLAYLIST_CAPACITY" TYPE="UInt32" >4</PREF>
	</MODULE>
	<MODULE NAME="EasyRelayModule" >
		<PREF NAME="local_ip_address" >127.0.0.1</PREF>
	</MODULE>
</CONFIGURATION>
